### ISSUE TITLE
Label text alignment

### ISSUE THREAD

**Issue by davidhund** [jxnblk/formula#1]
Nice work @jxnblk. I noticed an issue (tested in latest Chrome, Canary, Firefox and IE11): 

Labels ('extra elements') do not align with the text in the inputs.

Setting `line-height: 2` (factor: 'Total Height') and `vertical-align: middle` makes the label text align neatly with the input text.

**Comment by jxnblk** [comment]
Thanks! Hadn't checked all browsers after I'd made some changes to the Preview component. Apparently `overflow: hidden` was throwing that off, which I should've known better than to do. Should be fixed now but let me know if you see any other issues 😎
